apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: homelab-media-gpu-
  namespace: argo
  labels:
    app.kubernetes.io/component: homelab-media-gpu
    app.kubernetes.io/part-of: bluefin-test-suite
spec:
  workflowTemplateRef:
    name: homelab-media-gpu
