apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: homelab-media-service-
  namespace: argo
spec:
  serviceAccountName: argo
  workflowTemplateRef:
    name: homelab-media-service
  arguments:
    parameters:
      - name: lane
        value: "homelab-media-service"
      - name: branch
        value: "main"
