apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: homelab-print-service-
  namespace: argo
  labels:
    app.kubernetes.io/component: homelab-print-service
    app.kubernetes.io/part-of: bluefin-test-suite
spec:
  workflowTemplateRef:
    name: homelab-print-service
